### PR TITLE
fixing header column order

### PR DESCRIPTION
**Pull request by prashanth2692**
Fixing column header rendering order when combination of sortable and non-sortable columns are present.

### CODE REVIEW

**Review by bradshjw — CHANGES_REQUESTED** [review]
On line 13 you left a unassigned ng-if attribute. This also breaks the aria-sort attribute on the header column. Your changes would leave that attribute on the column header regardless whether the column was sortable or not. 

If your data columns and header columns are out of alignment, then we should take a look at why that is the case rather than altering sorting flags.

**Comment by prashanth2692** [comment]
My mistake, didn't notice the redundant ng-if, removed this ng-if. It appears to break the UI, but it works (else i would have noticed while testing in my local), nevertheless, it has to be removed. thanks for pointing it out.

Data columns are out of alignment because there are two ng-repeats, one for sortable columns and other for non-sortable columns. Due to this, the columns are grouped based on them being sortable or not.

**Comment by bradshjw** [comment]
I see what you mean now. My own testing had not revealed that initially, but after trying some different things I have been able to reproduce the error. 

I'll need to edit your commit a little in order to properly apply the aria-sort attribute and then I can merge it once I tested it locally.

**Comment by prashanth2692** [comment]
In my local i can see the aria-sort being applied properly. 
'none' for non-sortable and sortabled columns which aren't used for sorting.
ascending/descending - corresponding to sorting applied on the column.

**Comment by bradshjw** [comment]
The attribute shouldn't even be on the column header if they are not sortable. aria-sort:"none" means that the sort order hasn't been defined; it does not mean the column isn't sortable.

**Review by bradshjw — APPROVED** [review]
Changes tested with demo ng-table and ran unit tests.

**Pull request merged**
